package PART_II_OOP.Day45.Exceptions_GroupStudy;

public class F_RunTimeError {

	public static void main(String[] args) {
		
	}

	public static void go() {
		System.out.println("Going");
		go();
		
	}
}
